name: CI-CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master] 

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: bazel build //... 
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN  }}
        with:
          tag_name: v1.0.1
          release_name: Release v1.0.1
          body: |
            Release notes for v1.0.1
            - Feature 1: initial working app
            
      - name: Get apk path
        id: get_apk
        run: |
            apk_path=$(find bazel-bin -name '*.apk' -type f)
            ls
      
      - name: Upload Assets
        id: upload_assets
        uses: actions/upload-artifact@v2
        with:
          name: app-apk
          path: ${{ steps.get_apk.outputs.apk_path }}
          
          
