name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master] 

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: bazel build //... 
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            Release notes for v1.0.0
            - Feature 1: initial working app
      
      - name: Upload Assets
        id: upload_assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bazel-bin/src/main/
          asset_name: app.apk
          asset_content_type: application/vnd.android.package-archive
