name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master] 

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: bazel build //... 
